[package]
name = "elf-sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lxc = { version = "0.7.0", features = ["v4_0"]}
lxc-sys = "0.5.0"
sudo = "0.6.0"
