[tasks.run]
description = "Run"
script = ['''
cargo build
sudo lxc network create lxcbr0
sudo ./target/debug/elf-sandbox --target-elf-path /usr/bin/uname --timeout 10
sudo lxc network delete lxcbr0
''']