[tasks.run]
description = "Run"
script = ['''
cargo build
sudo brctl addbr lxcbr0
sudo brctl addif lxcbr0 $(ls $(find /sys/devices -name net | grep -v virtual | head -n 1))
sudo ip link set up dev lxcbr0
sudo dhclient -v lxcbr0
sudo ./target/debug/elf-sandbox --target-elf-path /usr/bin/uname
sudo ip link set up dev lxcbr0 down
sudo brctl delbr lxcbr0
''']

[tasks.sandbox-test]
description = "Test"
script = ['''
sudo brctl addbr lxcbr0
sudo brctl addif lxcbr0 $(ls $(find /sys/devices -name net | grep -v virtual | head -n 1))
sudo ip link set up dev lxcbr0
sudo dhclient -v lxcbr0
sudo lxc-create -t download -n sandbox -- -d ubuntu -r focal -a amd64
sudo lxc-start sandbox
sudo lxc-attach -n sandbox -- /bin/bash
sudo lxc-stop sandbox
sudo lxc-destroy sandbox
sudo ip link set up dev lxcbr0 down
sudo brctl delbr lxcbr0
''']

[tasks.destroy-container]
description = "Destroy container"
script = ['''
sudo ip link set up dev lxcbr0 down
sudo brctl delbr lxcbr0
sudo lxc-destroy sandbox
''']